### ISSUE TITLE
CSV-Datei für Postversand (DPAG-Internetmarken: Druck der Etiketten inkl. Briefmarke auf Briefumschlag)

### ISSUE THREAD

**Issue by npvkieckebusch** [fiedl/wingolfsplattform#67]
Guten Tag Bbr. Fiedlschuster,

demnächst steht ja wieder der Versand der Semesterprogramme an. Das ist bei uns jedes Mal eine Tortur. Ein Punkt habe ich mir da rausgesucht, welchen man verbessern könnte: man kann auf der Internetseite von der Deutschen Post die Briefmarken im Internet kaufen, dann packt man noch eine .csv-Datei (Empfänger-Daten) dazu und dann gibt einem die Deutsche Post die Möglichkeit die Briefumschläge mit Absender, Empfänger und fertiger Briefmarke zu bedrucken. Diese Möglichkeit könnte einem am Versand an Philister/Wingolfsverbindungen sehr viel Zeit/Arbeit sparen. 

Hierzu benötigt man allerdings eine sogenannte .csv-Datei - in einem ganz bestimmten Format. 
Man kann diese Möglichkeit hier finden: 
https://www.deutschepost.de/de/i/internetmarke-porto-drucken.html
Hier findet man die Musterdatei von der Deutschen Post: https://www.efiliale.de/efiliale/internetmarke/Briefe_mit_Adresse.csv

Zu dem Problem: die Wingolfsplattform gibt bereits .csv-Dateien aus, auch mit Adresse Name und allem, was man benötigt. Diese Datei funktioniert allerdings leider nicht mit der Internetseite der Deutschen Post.
Man müsste also einfach nur eine Datenbankabfrage machen, welche eine Ausgabe hat, sodass sie kompatibel ist für die Internetseite der Deutschen Post.

Ich würde mich sehr freuen, wenn dieser einfache aber effektive Entwicklungsschritt umgesetzt werden würde. Bitte fühle Dich frei mich jederzeit zu kontaktieren. E-Mail: b.q@hotmail.de, weitere Kontaktdaten sind auf der Plattform zu finden.

Mit bundesbrüderlichen Grüßen
Niels Paul v. Kieckebusch Dst!10 (xx,x)

**Comment by fiedl** [comment]
Gute Idee!

## Schritt 1: CSV-Export

Die Implementierung eines weiteren CSV-Tabellen-Formates, das den Spezifikationen der "Internetmarke" entspricht, sollte kein Problem sein.

https://www.efiliale.de/efiliale/internetmarke/Briefe_mit_Adresse.csv

Gibt es hierzu eine Deadline?

----

Intern: https://trello.com/c/AdnNNsdF/902-csv-export-fur-internetmarke

## Schritt 2: Generierung der Marken per API

Ein zweiter Schritt könnte die Erstellung der Marken ohne Zwischenschritt über einen CSV-Export sein. Die Plattform müsste dann direkt mit der API der DPAG kommunizieren.

Siehe etwa: http://www.vinett.de/post/internetmarke-uber-webservice/

Hierfür können wir

* (a) den einzelnen Administratoren gestatten, ihren eigenen Auth-Key des Internetmarken-Dienstes zu verknüpfen, sodass die Marken über ihr privates Konto bzw. das Verbindungskonto abgerechnet werden. Der technische Aufwand dürfte jedoch für den Anwender zu groß sein.
* (b) die Plattform über die Geschäftsstelle zentral bei der DPAG registrieren. Die Abrechnung der Marken erfolgte dann immer über das Konto der Geschäftsstelle. Dies können wir jedoch erst umsetzen, sobald die Kassenverwaltung implementiert ist, damit der Betrag dann automatisch der entsprechenden Verbindung in Rechnung gestellt werden kann.

**Comment by fiedl** [comment]
Ein erster Test-Import der produzierten CSV-Datei auf https://www.efiliale.de/efiliale/internetmarke ergibt eine Fehlermeldung:

**Die Spaltenkopfnamen in der ausgewählten CSV-Datei entsprechen nicht den gültigen Vorgaben. Bitte überprüfen Sie sie noch einmal.**

Die Fehlermeldung beschreibt jedoch nicht den tatsächlichen Fehler. Tatsächlich sind nicht die Spaltennamen das Problem, sondern das Encoding der CSV-Datei.

Während die Plattform standardmäßig nach **UTF-8** exportiert, benötigt der Dienst "Internetmarke" das **Encoding ISO 8859-1 (Western Latin 1)**.

Es muss also eine Fallunterscheidung implementiert werden, die die Internetmarken-CSV-Datei gemäß ISO 8859-1 exportiert.

**Comment by fiedl** [comment]
Erster Entwurf zur Benutzeroberfläche.

## CSV-Export für Internetmarken

<img width="509" alt="bildschirmfoto 2015-08-14 um 18 49 03" src="https://cloud.githubusercontent.com/assets/1679688/9279097/6778858e-42b5-11e5-8207-df9d195dafb7.png">

## Absender einstellen

Da der CSV-Export im Moment im Model-Layer verarbeitet wird, war es nicht möglich, per UI einen Absender abzufragen, der dann automatisch als Absender in die CSV-Tabelle eingetragen wird. Stattdessen muss der Absender händisch (mit einem Texteditor, Excel, o.ä.) in die Tabelle eingetragen werden, nachdem sie exportiert wurde.

Der Absender wird hierbei als erste Tabellenzeile eingetragen, wie in der Musterdatei der DPAG vorgeführt: https://www.efiliale.de/efiliale/internetmarke/Briefe_mit_Adresse.csv

Später ist auch das automatische Eintragen des exportierenden Administrators oder die Abfrage einer Absenderanschrift möglich; allerdings erst nach dem anstehenden Refactoring des Export-Systems.

**Comment by fiedl** [comment]
@npvkieckebusch: Die Funktion ist jetzt freigeschaltet. Bitte gib doch kurz Rückmeldung, ob alles, wie gewünscht, funktioniert.

**Comment by npvkieckebusch** [comment]
Vielen Dank für die schnelle Reaktion Bbr. Fiedlschuster! 

Ich habe das auch direkt mal ausprobiert, musste allerdings feststellen, dass es weiterhin einen Fehler gibt:
Man kann die Adresse nicht aktivieren. Ich habe auch bereits herausgefunden, woran das liegt: das Land muss in drei Buchstaben angegeben werden. Dann geht's. Also anstatt Deutschland DEU usw. 

Eine Sache ist mir auch gleich aufgefallen: Die erste Zeile ist der Absender. Könnte die .csv-Datei nicht direkt die Wingolfsverbindung als Absender enthalten? Dann müsste man die .csv-Datei nicht selbst bearbeiten. Dabei gibt es zwei Probleme: 
1. Öffnet man die .csv-Datei, wird sie zunächst automatisch mit Excel geöffnet. Wenn man die Datei mit Excel allerdings abspeichert (da man die Wingolfsverbindung als Absender eingeben muss), ist sie nicht mehr brauchbar.
2. Möchte man die .csv-Datei im Textedit bearbeiten, hat man Probleme mit den Umlauten. Wenn ich als Absender Darmstädter Wingolf reinschreiben möchte, muss ich zunächst herausfinden, wie das ä in diesem Format einzugeben ist.

Ein weiteres praktisches Problem: 
Wenn wir die Semesterprogramme versenden, dann gehen diese an die Alten Herren des Darmstädter Wingolf und an alle Philister, welche im BV25 leben. Das Problem ist, dass es hier nun Überschneidungen gibt: es gibt viele Alte Herren des Darmstädter Wingolf, welche auch im BV25 wohnen. Das bedeutet, wenn ich mir die Liste für die Philister des BV25 und die Liste für die Alten Herren des Darmstädter Wingolf runterlade, habe ich doppelte Briefe.
Könnte man sich eine überschneidungsfreie Liste ausgeben lassen?

Mit schwarz-weiß-gold'nen Grüßen,
Niels PvK Dst!10 (xx,x)

**Comment by fiedl** [comment]
@npvkieckebusch : 

* **Thema "DEU"**:
  
  > das Land muss in drei Buchstaben angegeben werden. Dann geht's. Also anstatt Deutschland DEU usw.
  
  Hier bräuchte ich eine Liste der von der Post gebräuchlichen Abkürzungen.
* **Absender automatisch eintragen**: Das geht, erfordert aber einiges an Programmieraufwand, da der jetzige Export-Mechanismus dazu nicht geeignet ist. Für den Moment kannst Du einfach einen Texteditor benutzen und die Datei mit dem Zeichensatz "ISO 8859-1 (Western Latin 1)" öffnen.

  Unter Linux benutzt Du hierfür *gedit*, unter Mac OS benutzt Du *[Textmate 2](http://macromates.com)*. @jreichardt : Wie macht man das unter Windows?

* **Vereinigungsmenge PhV + BV**: Das ist auch einfach möglich. Wir würden hierfür eine Adressatengruppe einrichten, ähnlich wie für die münstersche Zeitschrift: https://wingolfsplattform.org/groups/3612-adressaten-des-muensterschen-kiepenkerls/members. Schicke hierzu bitte eine Hilfe-Nachricht über den blauen Hilfe-Button ab. Dort müsstest Du auch schreiben, (a) wie eure Zeitschrift heißt, (b) wer die Zeitschrift alles bekommen soll.

**Comment by npvkieckebusch** [comment]
Also ich habe das eben noch mal mit einigen Ländern Stichprobenartig ausprobiert. Die Liste auf der folgenden Seite müsste die Liste sein, welche die dreistelligen Ländercodes beinhaltet:
http://www.hoefinger.ch/fotografie-mainmenu-33/tipps-und-tricks-mainmenu-51/176-liste-iso-lercode.html

Also es handelt sich um die Spalte Code2.

**Comment by npvkieckebusch** [comment]
Eine Sache fällt mir noch auf:
Die Titel fehlen. Ich bin mir sicher, dass sich einige Alte Herren melden werden, dass ihre Titel (wie Dr. Dipl.-Ing. usw) fehlen.
Kann man die noch davor machen?

**Comment by fiedl** [comment]
## Aktueller Stand

* [X] Grundlegende Implementierung fertig. Siehe Commits oben.

* [ ] **Thema "DEU"**: Erforderlich für korrekte Verarbeitung der Adressen.

  Problematischerweise liefert die GEO-API den dreistelligen Ländercode nicht mit, sondern nur den zweistelligen. https://developers.google.com/maps/documentation/geocoding/intro

  Im Notfall müssen wir die gängigen Codes auf unserem Server umrechnen. Die API gibt den Standard *ISO 3166-1-Alpha-2* zurück, die Post benötigt aber **ISO 3166-1-Alpha-3**.

  * Liste auf Wikipedia: https://de.wikipedia.org/wiki/ISO-3166-1-Kodierliste
  * Von der ISO gibt es hier eine Abfragemöglichkeit: http://www.iso.org/iso/iso-3166-1_decoding_table.html, allerdings nicht maschinen-auswertbar
  * http://gis.stackexchange.com/questions/1047/full-list-of-iso-alpha-2-and-iso-alpha-3-country-codes
  * Maschinen-auswertbarer Dump: http://download.geonames.org/export/dump/countryInfo.txt

  Aus letzterem Dump können wir eine Tabelle extrahieren.

* [ ] **Persönlichen Titel voranstellen**: Das ist möglich.

* [ ] **Absender automatisch eintragen**: Vorerst zurückgestellt, siehe oben.

* [ ] **Vereinigungsmenge PhV + BV**: Zielgruppe als Gruppe einrichten. Ticket: http://support.wingolfsplattform.org/tickets/214

**Comment by fiedl** [comment]
## Update

Der 3-stellige Länder-Code funktioniert nun, ebenso das Voranstellen des persönlichen Titles, sofern in das Feld "Persönlicher Titel" (`personal_title`) eingetragen.

## Zeichensatz-Problem

Es ist mir beim Test-Export jedoch ein Problem aufgefallen: Bei Adressen mit Zeichen, die im von der Post geforderten Zeichensatz nicht vorkommen, funktioniert der Export nicht und bricht gänzlich ab.

Der Benutzer sieht nur eine generische Meldung:

> 500 Internal Server Error
> If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

Im Log zeigt sich das tatsächliche Problem:

> An Encoding::UndefinedConversionError occurred in groups#show:
> U+2014 from UTF-8 to ISO-8859-1

Um das Problem zu lösen, können wir 

* (a) entweder alle nicht-kompatiblen Zeichen löschen; das können beispielsweise lange Bindestriche ("—") sein. Problematisch wird das, wenn man z.B. eine Adresse mit chinesischen Schriftzeichen eingibt.
* (b) die entsprechenden Adressen überspringen und den exportierenden Admin irgendwie daraufhinweisen, dass er die Adresse noch gesondert behandeln muss.

@npvkieckebusch : Das Problem ist, dass dieser Fehler sich prinzipiell nicht lösen lässt, da die Post den genannten Zeichensatz vorschreibt. Du kannst ja mal gucken, ob Deine Adressatenliste funktioniert oder ob bei euch problematische Adressen vorkommen.

**Comment by npvkieckebusch** [comment]
Also es funktioniert gut. Aber Probleme sind noch:

1. Bei einigen Alten Herren steht unter Zusatz: "" anstatt einfach nur nichts. Wenn "" da drin steht, gibt es einen Fehler. Wenn einfach nichts drin steht, funktioniert es gut.
2. Bei manchen international lebenden Alten Herren gibt die Datenbank nur leere Zellen aus, anstatt der Adresse. Straße, Nr, PLZ und Ort bleiben einfach leer. Schaut man allerdings in die Wingolfsplattform stehen dort Adressen. Beispiele: Radu Gruescu, Eugen Roth, Jörn Heinrich Sommer, Erik Zindel.

Ansonsten funktioniert alles gut.

Auf eine Sache muss man noch aufpassen: internationale Adressaten sollten zunächst nicht ausgewählt sein, da man bei der Option 62ct. ist und die DPAG den Briefmarkenwert nicht an den internationalen Briefmarkenwert anpasst. Man muss also erst mal nur die deutschen wählen, wenn man gerade bei der Option 62ct. ist und dann die internationalen extra wählen.

**Comment by fiedl** [comment]
## Zusammenfassung der offenen Punkte

* [ ] **Doppelte Anführungszeichen ("")** bei leeren Werten im CSV-Export: Dieses Problem wurde zwischenzeitlich technisch behoben (https://github.com/fiedl/your_platform/commit/53c55cb00f03556ac9fcb517094ba882a4858539); das Update wurde jedoch noch nicht live-geschaltet.

* [ ] **Leere Zeilen bei Auslandsadressen**: Diese Fehler sind darin begründet, dass die Adresskomponenten (Straße, Hausnummer, etc.) bei diesen Adressen von der Geo-API nicht erkannt werden.

  Diese Probleme können nur so gelöst werden, indem man die problematischen Adressen z.B. bei Google-Maps eingibt und das Format so lange variiert, bis die Adresse von Google-Maps korrekt erkannt wird. Wenn das der Fall ist, funktioniert auch die Erkennung mit der Plattform.

  Um solche Problemstellen zu identifizieren, gibt es für Administratoren eine Problem-Übersicht, aufzurufen über die rote Leiste oder direkt unter https://wingolfsplattform.org/issues.

  Dort taucht beispielsweise auch die Adresse von Phil. Zindel auf. Siehe geschwärztes Bildschirmfoto unterhalb.

  ![bildschirmfoto 2015-08-20 um 21 47 46](https://cloud.githubusercontent.com/assets/1679688/9393951/90cb2cf0-4785-11e5-8da4-0e061d436db3.png)

* [ ] **Internationale Adressen separieren**: @npvkieckebusch : Wie sollte der Prozess Deiner Ansicht nach ablaufen? Im Export-Menü separat *Inland* und *Ausland* auswählen, d.h. zwei verschiedene CSV-Dateien? Oder eine einzelne Datei, die aber nach Land sortiert ist?

**Comment by fiedl** [comment]
@npvkieckebusch : Ich habe soeben ein Update gefahren. Damit sollte das Problem mit den doppelten Anführungszeichen nun behoben sein. Viele Grüße! Sebastian

**Comment by npvkieckebusch** [comment]
Zu Inland/Ausland:
Also eine csv-Datei, in der eine Sortierung nach Aus- und Inländern erfolgt ist unnötig, denn wenn man sie auf der Seite der DPAG hochlädt, kann man die Datensätze sowieso beliebig sortieren (also die Spalten Name, Straße, Nation etc.). 
Daher würde ich tatsächlich eine Trennung der Listen in In- und Ausländer vorziehen. Dann kann es auch nicht ausversehen zu dem Fehler kommen, dass man fälschlicherweise eine 62ct. Marke auf eine internationale Adresse anwendet (diese benötigt 80ct.). Über kurz oder lang wird es mit Sicherheit jemanden geben, der diesen Fehler machen wird. Das bedeutet, dass eine Trennung der Listen mit großer Wahrscheinlichkeit Geld sparen wird ;-)

Zu internationalen Adressen:
Ich habe mir das mal angesehen: man gibt ja seine Adresse als freien Text ein. Ich denke, dass es doch viel mehr Sinn machen würde, wenn man Straße, Nummer, PLZ, Nation et cetera in die dafür bestimmten Felder eingibt. Dann definiert man quasi bei der Eingabe seiner Adresse direkt, was auf den Brief als Adresse gedruckt wird. Dann wird es auch nicht zu Fehlern mit leeren Adress-Zeilen kommen.

**Comment by fiedl** [comment]
* **Internationale Adressen separieren**: @npvkieckebusch : Erledigt. Guck Dir mal an, ob das so klappt.
* **Separate Felder für die Adressbestandteile** (Straße, Hausnummer, PLZ, Stadt, …): Von dieser Eingabemethode sind wir absichtlich weggegangen, da Auslandsadressen in der Regel anders formatiert werden als die deutschen Adressen.

  Beispielsweise hat ein Auslandsphilister herausgefunden, dass seine Adresse genau so formatiert sein muss, damit die Post ankommt. Von daher schien es uns logisch, die Adresse als ganzes Feld zu betrachten.

  ![48aa946e-3cf6-11e4-9978-bbd4d00f3da9](https://cloud.githubusercontent.com/assets/1679688/9412994/76ce54bc-482f-11e5-97ae-79ccdfcfc148.png)

  Wenn man für Serienbriefe und den Adress-Export die Adresse weiterhin als ganzes Feld betrachtet, läuft alles optimal. Probleme gibt es erst, seit dem wir versuchen, z.B. für den DPAG-Export, die Felder wieder zu trennen. Hierzu nutzen wir eine Geo-API, die wir ohnehin für das Karten-Feature verwenden. Die Geo-API erkennt aber nicht alle Adressen korrekt.

  Ich gebe das Thema nocheinmal als separaten Vorgang mit in die nächste Sitzung. Vielleicht fällt uns hierzu noch eine sinnvolle Lösung ein. Auf die Schnelle wird da aber nichts zu machen sein.

**Comment by npvkieckebusch** [comment]
Jetzt gibt es gerade ein Problem mit den Umlauten. In der csv-Datei stehen jetzt die Umlaute und nicht die seltsamen entsprechenden Zeichen für die Umlaute. Also alle Adressen mit Umlauten sind nun rot markiert und somit nicht auswählbar.

**Comment by npvkieckebusch** [comment]
Separate Felder für die Adressbestandteile:
Wenn man das Problem hat, dass man eine so spezielle Adresse hat, dass es damit nicht passt, dann könnte man doch bei der Adresseingabe eine Auswahl implementieren: 1. Normale Adresse: Man gibt den Straßennamen und Nummer und PLZ ein, 2. Spezielle Adresse: man kann seine Adresse in ein freies Feld eintragen.

**Comment by fiedl** [comment]
> Jetzt gibt es gerade ein Problem mit den Umlauten. In der csv-Datei stehen jetzt die Umlaute und nicht die seltsamen entsprechenden Zeichen für die Umlaute. Also alle Adressen mit Umlauten sind nun rot markiert und somit nicht auswählbar.

@npvkieckebusch : Danke für den Hinweis mit den Umlauten. Das Problem ist nun behoben.

Du sprichst aber von seltsamen Zeichen in der CSV-Datei. Die Umlaute siehst Du nur als "seltsame Zeichen", da in Deinem Texteditor der falsche Zeichensatz ausgewählt ist.

> Für den Moment kannst Du einfach einen Texteditor benutzen und die Datei mit dem Zeichensatz "ISO 8859-1 (Western Latin 1)" öffnen.

>   Unter Linux benutzt Du hierfür *gedit*, unter Mac OS benutzt Du *[Textmate 2](http://macromates.com)*. @jreichardt : Wie macht man das unter Windows?

So sieht das bei mir im Texteditor aus, wenn ich versuche, die CSV-Datei zu öffnen:

<img width="1060" alt="bildschirmfoto 2015-08-21 um 20 00 57" src="https://cloud.githubusercontent.com/assets/1679688/9415551/6b045c9c-4840-11e5-970c-23d75ff9110a.png">

**Comment by fiedl** [comment]
@jreichardt @jbx26 : Nocheinmal die Nachfrage: Wie kann man denn unter Windows eine Textdatei (CSV) mit Zeichensatz "ISO 8859-1 (Western Latin 1)" öffnen und bearbeiten, sodass sie danach im gleichen Zeichensatz wieder abgespeichert wird? LG Fiedl

**Comment by npvkieckebusch** [comment]
Wow! Spitze! Nun funktioniert wirklich alles bestens! =) 
Vielen vielen Dank an Dich Bbr. Fiedlschuster! Und auch, dass Du das nun noch alles so kurz vor Deinem Urlaub gemacht hast. Ich hoffe Du kannst Dich sehr erholen!
Ja... "komische Zeichen" halt ;-) Hatte das nicht ganz verstanden. Danke aber, ich wusste nicht, dass ich mir Textmate 2 runterladen muss. Ich hatte die ganze Zeit nach einer Textformatierung oder sowas ähnlichem gesucht.

**Comment by jreichardt** [comment]
@fiedl Wir hatten das Thema schon mal, erinnerst du dich? Notepad kommt überhaupt nicht mit anderen Encodings klar, und Excel (das Standardprogramm für CSV unter Windows) erwartet einen BOM als Tip für das verwendete Encoding. Es gibt natürlich Third-Party-Editoren, die deutlich besser sind, etwa Notepad++. Da kann man das Encoding einstellen. Aber weder das Dateisystem noch das CSV Format erlauben mWn eine Persistierung des verwendeten Encodings.

**Comment by fiedl** [comment]
@jreichardt : Danke für die Empfehlung von **Notepad++**.

Den BOM konnte ich hier keine Anwendung finden lassen, da die DPAG-Web-Anwendung damit nicht klar kam. Deswegen mussten wir ja überhaupt auf das ungewöhnliche Encoding ausweichen.

Damit schließe ich dieses Issue. Die Fortsetzung liegt im Refactoring des Export-Mechanismus (https://trello.com/c/r427f7K7/903-listexport-refaktorieren). In diesem Zusammenhang können wir später auch die automatische Anpassung des Absenders für DPAG-Internetmarken einführen.
