### ISSUE TITLE
Reload-Balken stört

### ISSUE THREAD

**Issue by maiksd** [fiedl/wingolfsplattform#68]
Alle paar Sekunden läuft am oberen Bildschirmrand ein weißer Reload-Balken durchs Bild und lenkt vom Lesen ab. Ich finde das ziemlich störend, kann das nicht unsichtbar stattfinden?

**Comment by fiedl** [comment]
Das ist ein Bug beim Anzeigen von Posts (posts#show). Danke für den Hinweis.

**Comment by fiedl** [comment]
@maiksd Der Fix ist jetzt live. LG Fiedl

**Comment by maiksd** [comment]
Prima, danke
