### ISSUE TITLE
Option in Profile for privacy

### ISSUE THREAD

**Issue by Liwindo** [fiedl/wingolfsplattform#69]
At the moment you can see what every member is doing in the plattform. It would be great to implement an option for deactivating that.

**Comment by fiedl** [comment]
To deactivate the ui feature itself, just override the partial `app/views/last_seen_activities/_index.html.haml`.

If a specific user does not want to be seen, he can activate **incognito mode** in his user settings.

<img width="909" alt="bildschirmfoto 2016-03-05 um 12 20 02" src="https://cloud.githubusercontent.com/assets/1679688/13547283/e87869a8-e2cc-11e5-87f8-d3a1bd5a2d5a.png">

<img width="901" alt="bildschirmfoto 2016-03-05 um 12 20 43" src="https://cloud.githubusercontent.com/assets/1679688/13547286/fa11715a-e2cc-11e5-9062-9e9f05087ce4.png">

To prevent any status data from being collected, override the `set_current_activity` method in `app/controllers/concerns/current_activity.rb`.
